package:
  name: taxcalc
  version: 0.4

requirements:
  build:
    - pytest
    - setuptools
    - python
    - numpy
    - pandas <=0.18.0
    - numba
    - toolz
    - six
  run:
    - pytest
    - setuptools
    - python
    - numpy
    - pandas <=0.18.0
    - numba
    - toolz
    - six

about:
  home: http://www.github.com/OpenSourcePolicyCenter
