package:
  name: taxcalc
  version: 0.2

requirements:
  build:
    - pytest
    - setuptools
    - python
    - numpy
    - pandas
    - numba
    - toolz
  run:
    - pytest
    - setuptools
    - python
    - numpy
    - pandas
    - numba
    - toolz

about:
  home: http://www.github.com/OpenSourcePolicyCenter
